### ISSUE TITLE
Clean Todo 

### ISSUE THREAD

**Issue by AlexandreGazagnes** [Razvan-drb/Projet_04_OC#7]
- [ ] Tackle update  tournament problem => we want score OK 1/0 not -1 -1 in the rounds.json !!!! 
- [ ] What abour computing results by player ????
- [ ] write proto AND OR code about thi feature
